[model]
model_name = "Qwen/Qwen3-VL-2B"
model_config = "configs/models/qwen3_vl_2b.json"
train_vit = true
train_llm = true
train_mlp = true

[wandb]
run_name = "qwen3_vl_2b"
project_name = "qwen3_vl_jupiter"
entity_name = "bsc_runs"
log_topk = false

[training]
model_dir = "/e/project1/reformo/ockier1/qwen_models/qwen3_vl_2b"
chat_template = "NULL"
output_dir = "/e/scratch/open-sci-mm/ockier1/checkpoints/qwen3_vl_2b"
save_steps = 1000
total_steps = 10000
random_init = false
scheduler_type = "cosine"
warmup_steps = 100

lr_llm = 1e-5
lr_mlp = 1e-5
lr_vit = 1e-6

tp_size = 2

data_parallel = "fsdp"
reshard_after_forward = "never"

compile = true
dynamo_recompile_limit = 64

tpi_multiplier = 1
adamw_impl = "fused"
adamw_stochastic_round = false
adam_betas = [0.9, 0.95]
weight_decay = 0.1
master_dtype = "float32"

grad_reduce_dtype = "float32"
deterministic = false
clear_cache_vram = 0

resume_checkpoint = true

[data]
data_path = "/e/scratch/open-sci-mm/ockier1/vlm_datasets/plotqa_cot"
seq_len = 32768
tokens_per_microbatch = 0
shuffle_buffer_size = 1000
packing_buffer_size = 100
max_samples_per_sequence = 100
repeat = true
save_dataloader_state = true